COQVERSION = $(shell $(COQBIN)coqtop -v | head -1 | grep -E '(trunk|master)' | wc -l | sed 's/ *//g')

ifneq "$(COQVERSION)" "0"
COQVERSION = trunk
else
COQVERSION = $(shell $(COQBIN)coqtop -v | head -1 | sed 's/.*version \([0-9]\.[0-9]\)[^ ]* .*/\1/')
endif
