This directory contains Dockerfiles to create new Docker images for
running Verdi tests reproducibly.

The rest of this file explains how to build new Docker images:


Preliminaries:

  # Finish docker setup if necessary.
  sudo usermod -aG docker $(whoami)
  # Then log out and back in.

  # Obtain Docker credentials.
  # (This is only necessary once per machine; credentials are cached.)
  docker login


Create the Docker image:

# Create the Docker image, in an empty directory, and upload to Docker Hub.
alias create_upload_docker_image=' \
  rm -rf dockerdir && \
  mkdir -p dockerdir && \
  (cd dockerdir && \
  \cp -pf ../Dockerfile-$OS-$COQVER Dockerfile && \
  docker build -t mdernst/$OS-for-$PROJECT-$COQVER . && \
  docker push mdernst/$OS-for-$PROJECT-$COQVER) && \
  rm -rf dockerdir'

export OS=trusty
export COQVER=coq8.6
export PROJECT=verdi
create_upload_docker_image

export OS=trusty
export COQVER=coq8.7
export PROJECT=verdi
create_upload_docker_image

export OS=xenial
export COQVER=coq8.6
export PROJECT=verdi
create_upload_docker_image

export OS=xenial
export COQVER=coq8.7
export PROJECT=verdi
create_upload_docker_image


Cleanup:

After creating docker images, consider deleting the docker containers,
which can take up a lot of disk space.
To stop and remove/delete all docker containers:
  docker stop $(docker ps -a -q)
  docker rm $(docker ps -a -q)
or you can just remove some of them.
